### ISSUE TITLE
Parallel code generation

### ISSUE THREAD

**Issue by vifactor** [Pelagicore/facelift#132]
It looks like code generation from different interface files happens independently and is  trivially parallelazable on  a pool of multiple processes. For projects with big number of interface files/modules it may be worth to use more than one thread for code generation.

**Comment by jacky309** [comment]
Parallelization is only possible if the code generation happens at build time instead of configure time. Since the list of generated files is needed at configure time (the generated headers have to be MOCed), the code generator has to be called sequentially at configure time anyway, in order to generate the list of files.

**Comment by vifactor** [comment]
I might be wrong, but headers are MOCed (even at configure time) after the script facelift-codegen.py finished to work, are they?

If so the for-loop(s) inside run_generation function can be parallelized, e.g. by executing generateFile method on independent interface files in several processes created via multiprocessing (or other similar) python package.
